version: '3.7'

services:
  web:
    build: .
    container_name: tic_tac_toe_frontend
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - .:/app
    networks:
      - tic_tac_toe_network

networks:
  tic_tac_toe_network:
    driver: bridge
